<img src="https://i.imgur.com/d28OeSq.png" width="350px" align="right">

# Finance with Python Video 2 

Credit to Dr. Yves Hilpisch of The Python Quants GmBH for instructional material

In [1]:
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt

## Option Replication and Pricing

In [2]:
'''Stocks'''
S = np.array((20., 5.)) 

In [3]:
'''S at time zero'''
S0 = 10.

In [4]:
'''Riskless bond asset'''
B = np.array((11.,11.))

In [5]:
'''Bond at time zero'''
B0 = 10.

In [6]:
'''Market matrix'''
M = np.array((S, B)).T
M

array([[20., 11.],
       [ 5., 11.]])

In [7]:
'''Market price vector'''
M0 = np.array((S0,B0)).T
M0

array([10., 10.])

In [8]:
0.5 * S - 0.5 * B

array([ 4.5, -3. ])

In [9]:
K = 15. # strike price of call option
C = np.maximum (S - K, 0) # payoff of call option
C

array([5., 0.])

In [10]:
'''Solve for the optimal portfolio'''
'''shows we should long .33 bond and short the bond .1515 this 
is not replicable in the real world because of partial shares isssues'''
phi = np.linalg.solve(M, C) # solving for M(market) & C(Call Option)
phi #replication portfolio

array([ 0.33333333, -0.15151515])

In [11]:
np.dot(M, phi)# portfolio payoff = option payoff

array([5.00000000e+00, 2.22044605e-16])

In [12]:
C0 = np.dot(M0, phi)# cost to set up portfolio
C0

1.8181818181818188

1.818 is the arbitrage free price of the option 

## Fundamental Theorem of Asset Pricing

Is a martingale measure and the absence of arbitrage are equivalent
http://pi.math.cornell.edu/~mec/Summer2008/spulido/fftap.html

### Probability Measure and Expectation 

In [13]:
'''explicit modeling represented as 2d matrix; up & down where P == Up state'''
P = 0.5
P = np.array((P, 1 - P))
P

array([0.5, 0.5])

In [14]:
'''expected value of S'''
ES = np.dot(S, P)
ES

12.5

In [15]:
'''expected value of B'''
EB = np.dot(B,P)
EB

11.0

### Maritingale Property 

In [16]:
'''interest rate'''
i = 0.1

df = 1 / (1 + i)
df

0.9090909090909091

$Q$ is called a Martingale measure if 

> $\frac{1}{1+i}\cdot E^Q(S_1) = S_0$    

holds

In [17]:
df * np.dot(S, P)

11.363636363636363

In [18]:
S0 # we are looking for S0, the above did not give 10.0
# under P, the price process was not a price process

10.0

## Deriving a Martingale Measure 

In [19]:
'''minimize an error measure under a constraint'''
from scipy.optimize import minimize

In [20]:
'''derive an error measure'''
def error (Q):
    return (np.dot(S, Q) / (1+i) - S0) ** 2 # add the square for convex optimizers; a differentiable smooth function

In [21]:
'''call error on P, the up|down 2d matrix'''
error(P)

1.859504132231404

In [22]:
'''constraint: the sum of the two vectors need to add to 1'''
'''type equation function: lambda Q: Q is supposed to == 1'''
cons = ({'type': 'eq', 'fun': lambda Q: Q.sum() - 1}) #this is a probability constraint

In [23]:
'''boundaries: 2 elements over which we are going to optimize & the prob measure shall be between 0 and 1'''
bnds = ((0,1),(0,1))

In [24]:
''''''
res = minimize(error,(0.5, 0.5), bounds=bnds, constraints=cons)
res

     fun: 1.0172028584007344e-14
     jac: array([ 1.25849558e-06, -6.09001821e-07])
 message: 'Optimization terminated successfully.'
    nfev: 9
     nit: 2
    njev: 2
  status: 0
 success: True
       x: array([0.39999999, 0.60000001])

In [25]:
round(res['fun'], 5)

0.0

In [26]:
# x is from array shown above
Q = res['x']
Q

array([0.39999999, 0.60000001])

In [27]:
error(Q)

1.0172028584007344e-14

In [28]:
np.dot(S,Q) / (1 + i)

9.999999899143525

In [29]:
S0

10.0

### Risk Neutral ('Martingale') Pricing 

In [30]:
phi

array([ 0.33333333, -0.15151515])

In [31]:
np.dot(M, phi)

array([5.00000000e+00, 2.22044605e-16])

In [32]:
np.dot(M0, phi)

1.8181818181818188

In [33]:
np.dot(C, P) / (1 + i) # wrong measure OR wrong discount rate

2.2727272727272725

In [34]:
np.dot(C, Q) / (1 + i) # martingale meas in combo with risk free rate

1.8181817845629937

### Aproximation by Ordinary Least Squares

In [35]:
'''same as phi & np.linalg.solve'''
reg = np.linalg.lstsq(M,C)[0]
reg

/anaconda3/lib/python3.7/site-packages/ipykernel_launcher.py:2: FutureWarning: `rcond` parameter will change to the default of machine precision times ``max(M, N)`` where M and N are the input matrix dimensions.
To use the future default and silence this warning we advise to pass `rcond=None`, to keep using the old, explicitly pass `rcond=-1`.
  


array([ 0.33333333, -0.15151515])

In [36]:
np.dot(M, reg)

array([5.00000000e+00, 6.66133815e-16])

In [37]:
np.dot(M0, reg)

1.8181818181818188

### Option Pricing Based on Neural Nets ("Learning')

In [38]:
M # layer 0

array([[20., 11.],
       [ 5., 11.]])

In [39]:
'''guessing the portfolio by replication with neural nets'''
'''initial weights vector'''
w = np.array((1., -1.))

In [40]:
'''layer 1'''
layer1 = np.dot(M, w)  
layer1

array([ 9., -6.])

In [41]:
'''deltas'''
d = layer1 - C
d

array([ 4., -6.])

In [42]:
'''mean squared error'''
(d ** 2).mean()

26.0

In [43]:
'''set alpha to [x]'''
alpha = 0.01

In [44]:
'''update the weight vector - the "learning" step '''
w -= alpha * d # with in place substraction
w

array([ 0.96, -0.94])

In [45]:
for _ in range(150):  # range needs to be 150 for teaching purposes :: matches arb free price of ~1.818 at 150
    layer1 = np.dot(M, w)
    d = layer1 - C
    print((d ** 2).mean())
    w -= alpha * d

22.7956
19.961021860000002
17.457452107065993
15.250618412184856
13.30936408577991
11.60507649520492
10.111481421813131
8.804566373317922
7.6625264792585455
6.665692134082745
5.7964285834261675
5.039010883039852
4.379482091822218
3.8055029321912013
3.3061998862007806
2.8720169752269555
2.4945748244864405
2.1665392411974533
1.88150047883408
1.6338635928641287
1.4187497647794394
1.2319081274028374
1.0696374176220944
0.9287166738543854
0.8063441544369638
0.7000836571405773
0.6078174526479784
0.5277050944433831
0.4581474260178029
0.397755168139082
0.3453215305859752
0.299798351962883
0.2602753266862044
0.22596192928857556
0.19617169257004025
0.17030853785498823
0.14785489287913103
0.12836136591860176
0.11143777401974464
0.09674534894766645
0.08398996709606393
0.07291626942715977
0.06330255485360142
0.054956345623050094
0.04771053648308851
0.04142005092460259
0.03595893783602279
0.031217850635158258
0.027101858544419332
0.023528546283895203
0.02042636420225479
0.017733195859141886
0.0153951

In [46]:
w

array([ 0.33334948, -0.15153449])

In [47]:
layer1 = np.dot(M, w)
layer1.round(5)

array([ 5.00011e+00, -1.30000e-04])

In [48]:
np.dot(M0, w)

1.8181498972598868

## What was going on above: 

__Image credits to Dr. Yves Hilpisch and The Python Quants__

<img src="https://i.imgur.com/z96a78Z.png" width="720px" align="center">

<img src="https://i.imgur.com/gbscHEI.png" width="720px" align="center">

## Mean-Variance Portfolio Theory 

In [49]:
'''Array of 3 Stock Payoffs '''
S = np.array((20, 10, 5.))
'''Array of 3 Riskless Payoffs '''
B = np.array((11., 11, 11))
'''Call Option'''
C = np.maximum(S - K, 0)
'''Market'''
M = np.array((S, B, C)).T
M

array([[20., 11.,  5.],
       [10., 11.,  0.],
       [ 5., 11.,  0.]])

In [50]:
'''all rows and first 2 columns'''
M[:, :2]

array([[20., 11.],
       [10., 11.],
       [ 5., 11.]])

In [51]:
reg = np.linalg.lstsq(M[:,:2], C, rcond=None)[0] # had to pass rcond to stop update msg
reg

array([ 0.35714286, -0.22727273])

In [52]:
'''3 payoff state least squares regression'''
np.dot(M[:,:2], reg)

array([ 4.64285714,  1.07142857, -0.71428571])

In [53]:
'''another numerical check with exact solver replicating zero vector'''
np.linalg.solve(M, np.array((0, 0, 0)))

array([ 0.,  0., -0.])

In [54]:
'''another numerical check with exact solver replicating another vector for complete market'''
np.linalg.solve(M, np.array((1, 2, 3)))

array([-0.2       ,  0.36363636,  0.2       ])

## Returns 

In [55]:
'''option payoff is non-redudant cannot use replication arguments IOT come up with unique arb free price'''
'''3-sum vector'''
C0 = 1.25 # <--- Option Payoff
M0 = np.array((S0, B0, C0))
M0

array([10.  , 10.  ,  1.25])

In [56]:
'''Market Matrix'''
M

array([[20., 11.,  5.],
       [10., 11.,  0.],
       [ 5., 11.,  0.]])

In [57]:
'''Return Matrix'''
R = M / M0 -1
R

array([[ 1. ,  0.1,  3. ],
       [ 0. ,  0.1, -1. ],
       [-0.5,  0.1, -1. ]])

In [58]:
'''setting a probability vector'''
P = np.ones(3) / 3
P

array([0.33333333, 0.33333333, 0.33333333])

In [59]:
'''assign R.mean to a vector variable'''
r = R.mean(axis=0) # stock, bonds, option

## Portfolio Return

In [60]:
'''portfolio weights assumed to add up to 1'''
phi = np.array((0.3, 0.4, 0.3))

In [61]:
'''the portfolio return'''
np.dot(r, phi)

0.19

## Volatilities 

Generally defined as the standard deviation of the returns

In [62]:
'''R is the returns matrix'''
R

array([[ 1. ,  0.1,  3. ],
       [ 0. ,  0.1, -1. ],
       [-0.5,  0.1, -1. ]])

In [63]:
R.std(axis=0) # stocks, bonds, option :: simple model structure and rather extreme S & C values

array([0.62360956, 0.        , 1.88561808])

<img src="https://i.imgur.com/d28OeSq.png" width="350px" align="right">